spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: off

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://macro-db.cd6gc4wm6h7v.ap-northeast-2.rds.amazonaws.com:3306/thunder?serverTimezone=UTC
    username: admin
    password: secret1!

  config:
    import:
      - classpath:client.yml
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"